module.exports = {
  SENDER_EMAIL:
    "PLACE YOUR EMAIL ADRESS FROM WHICH YOU WANT TO SEND NOTIFICATIONS",
  SENDER_PASS: "PLACE THAT EMAIL'S PASSWORD HERE",
  BOT_TOKEN: "PLACE YOUR TELEGRAM BOT TOKEN HERE",
  MONGO_URI: "PLACE YOUR MONGODB'S COLLECTION'S URL HERE",
};
